# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f09dd9bb8eab3d7ab31539633cb8431611f5724864d6d83493ad0f709997051442b0fc5dd00b6ec9069a3ea490d5bdee03126f329c95fc83772d141efaf252c

test:
  secret_key_base: 4f7334c4306ca07eb62d0b677f426a4320767576c11c24a52a01e954d2206f2884c078a01a3b2c731f53a4c8ca7d8c5ff9329e8ba288665b8a98cb1f530eedf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
